export default {

	ZONES_RECEIVED: 'ZONES_RECEIVED',
	ZONE_CREATED: 'ZONE_CREATED',
	SELECT_ZONE: 'SELECT_ZONE',
	COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
	COMMENT_CREATED: 'COMMENT_CREATED',
	COMMENT_UPDATED: 'COMMENT_UPDATED',
	CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
	CURRENT_USER_UPDATED: 'CURRENT_USER_UPDATED',
	PROFILE_RECEIVED: 'PROFILE_RECEIVED',
	PROFILE_UPDATED: 'PROFILE_UPDATED',
	APPLICATION_STATE: 'APPLICATION_STATE'

}
